### ISSUE TITLE
l10n_nl_tax_invoice_basis tax booking should be on invoice date

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/l10n-netherlands#137]
Hi,

Example:
Invoice date = 04-01-2018
Accounting date = 31-12-2017

Odoo will book everything on 31-12-2017 including the tax. The tax statement report will be correct, but the balance on the tax statement will be incorrect matched to the balance on the ledger. 
In the booking the accounting date of the tax moves should be 04-01-2018.

With kind regards,
Cas

**Comment by yung-wang** [comment]
Hi Cas,

This is how Odoo standard works. In this module we didn't touch the accounting date, we added extra fields in the move lines to make it work only with the Tax Statement (OCA module). The reason is that we don't want to break standard Odoo functionality.

We had the same discussion with Laura and Fabien in the Odoo localisation.

[https://github.com/odoo/odoo/issues/18572](url)

So this module is only created to support the OCA tax statement.

Grt,
Yung-Wa

**Comment by CasVissers-360ERP** [comment]
Thnx for the clarification Yung-Wa. Ticket closed.
