### ISSUE TITLE
New OCA representative (aka. project leader)

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/l10n-netherlands#32]
From LinkedIn I understand that @diellenne is no longer working in the Odoo area, so I wanted to propose @hbrunn as the next OCA representative for this project.

Holger is one of the most active Odoo developers in the OCA. He wrote three of the four modules in the 8.0 branch of this repository.

**Comment by diellenne** [comment]
Yes, I quit Onestein BV and I'm not working around Odoo anymore...at least not in my professional life. As reported on the OCA website (unavailable at the moment) @pankk has been appointed as new OCA representative.

Regards

**Comment by StefanRijnhart** [comment]
Given the total absence of activity in the whole OCA I don't think @pankk qualifies, to be honest.

**Comment by pankk** [comment]
I've been fully booked on projects at Onestein BV, but will work more on OCA in the near future.

**Comment by diellenne** [comment]
The only thing I can say is that personally I fully support @pankk for the role: I had the pleasure to closely work with him in the last two years and I think that he is skilled, responsible and dedicated enough to make a really good job as OCA representative.

**Comment by acde55** [comment]
Well that's  what Onestein-people said about you also before you started, however it didn't work out that way, did it?  Many people have lots of good intentions but I propose to look at the facts this time.

**Comment by pedrobaeza** [comment]
I have to say that the sequence should be that way: first contribute and prove your intentions, and then receive the credits and apply for the representation.

**Comment by ghost** [comment]
Stefan, we will still be the project manager of the Dutch localization since we have the accounting knowledge in the Netherlands and as the only Dutch  organization with academic knowledge  regarding this subject. 

But of course you can join.

**Comment by ghost** [comment]
Acde5: im sorry but what's going on?i don't know who you are and how could you accuse us saying something that we didn't? We have a strong relationship with the former Therp and Stefan?

**Comment by ghost** [comment]
Stefan, I'll call you tomorrow and let's sort this out tomorrow. Texting will not help anybody. Have a good evening.

**Comment by ghost** [comment]
Kevin is just fully booked for the next few days there is no reason to doubt anything.

**Comment by StefanRijnhart** [comment]
@samernefawa Don't bother calling me please. Onestein has done a very poor job managing this project so far so I would like to leave it to a party with proven commitment.

**Comment by ghost** [comment]
ONESTEiN as responsible for the Dutch localization we make use of our academic accounting knowledge to improve Dutch accounting, it could be managing the process, initiating an idea which not always visible, or working on the code. It's important to look from both the functional as the Technical side as coding only one of the important elements besides understanding the process from functionality and legal perspectives. Both are complementary.

ONESTEiN keeps an eye on the Dutch regulations and tries to translate these into Odoo,  these functionalities could be coded by different parties. All help is more than welcome, end of 2015 a sprint took place in our  location devoted for OCA, of course you can't see our name as an organizer but those who coded who are from other Odoo partners,  many thanks for them. Anew Sprint Dutch we be organized soon too. We have the space and the resources to organize the springs and we will keep doing that. 

As part of the Dutch localzation network, we work hard on collecting the needs of the Dutch client to make these visible in Odoo, this is an example of of our efforts in collaboration with other devoted Dutch Odoo partners.  
https://odoonetwerk.nl/

Have a good evening all. 

For message indirectly related, please send me a private message.

**Comment by gfcapalbo** [comment]
I agree with pedro , i believe the person who contributes the most is most qualified to take over.

**Comment by pedrobaeza** [comment]
@samernefawa, I agree that your company can be very qualified, and has mounted a dutch partner network about that, but this is OCA, and the facts that count are the contributions made to it. I can't see much of these contributions from any of your people, and they don't have to be technical ones. You can write blueprints for instructing how to develop some specific accounting methods. Maybe I'm wrong, so please show me a list of these contributions. If not, I stand in supporting the one that I see that contributes.

**Comment by gfcapalbo** [comment]
:+1:

**Comment by ghost** [comment]
Sure the most contributes are most desired .. True, have a good evening.

**Comment by diellenne** [comment]
Dear @acde55 ,

I'm replying to you just because you publicly referred directly to me; I don't think that if the project is going slow is fault of the OCA Representative...or at least not all of it; we already discussed about it and made our 'Mea Culpa' but you are free to think what you prefer.
Anyway if you have so much to complain you could simply come out months ago (not just now that a new responsible is needed), since when Onestein decided to PROPOSE the Dutch localization project, or you could join the sprint organized and founded by Onestein mainly to decide a common strategy in order to be more fast and effective; or talking about contribution, you can even directly contribute somehow...from what I can see you never did anything on OCA projects or on any other Open Source ones.
Said that, I really have better things to do instead of staying here discussing with you! I really feel I have nothing to justify anymore...I don't even know who you are and honestly I can't care less.
I gave my opinion and the OCA members are free to appoint for the role the person that will be considered the best fit for it.

Regards,
D

**Comment by ghost** [comment]
Please hold your horses everybody, it seems that everybody willing to work for the benefits of  OCA. 
 That's wonderful,  let's try to organize  to maximize the benefits. 

 For the time being I wish you great evening. 
 Send me a personal email if you are willing to maximize the benefits towards OCA  we can work on that together.

**Comment by andreschenkels** [comment]
I see a lot more contributions coming from Onestein and I know @pankk will do a good job.

**Comment by ploegvde** [comment]
Let's support @pankk and all move forward!

**Comment by hbrunn** [comment]
I don't understand what's to discuss when looking at https://github.com/OCA/l10n-netherlands/graphs/contributors

**Comment by PCatinean** [comment]
I cannot speak for other contributors since I do not know them personally or online (my shortcoming here).All I can say is that I vouch for @hbrunn as he is a top-notch developer, valued and frequent contributor to OCA (as the numbers also show).I personally work with him and witnessing first-hand his experience and dedication towards opensource and education of others

Again, no disrespect or disconsideration to anyone else that may be very well qualified for the job as well

**Comment by gurneyalex** [comment]
in terms of knowledge of the OCA processes and implication in the OCA projects, @hbrunn is clearly a better candidate. Let @pankk learn the ways of the OCA projects, let him do some reviews, participate and get involved and _then_ maybe he can say he'd like to be the PSC representative. As of today, he only has participated on 3 different PRs on this project which seems quite low to me.

**Comment by legalsylvain** [comment]
:+1: with @gurneyalex, @pedrobaeza, @StefanRijnhart arguments.

@ploegvde : I'm not sure that 'support' is a good term. This is not an election. It is about who has the best qualities to be an OCA representative. Saw @hbrunn activities in OCA (generaly and in this project), I don't see any reason to choose someone else.

Kind regards.

**Comment by max3903** [comment]
It is not an election or vote of popularity, it is a meritocracy and as of today @hbrunn deserves to be the OCA representative more than anyone else when objectively looking at:
https://github.com/OCA/l10n-netherlands/graphs/contributors

**Comment by sebastienbeau** [comment]
I agree with @gurneyalex @max3903 @StefanRijnhart @pedrobaeza 
@hbrunn have a great knowledge of OCA and also a good experience (see git history) on this project so as the rule is the meritocracy, I think for now that @hbrunn is the best for the job.

**Comment by elicoidal** [comment]
:+1: for @hbrunn

**Comment by RoelAdriaans** [comment]
That graph is a bit misleading because it's for the 9.0 branch only. 
(Contributions to 9.0, excluding merge commits)

But, with a bit of git magic, for the 8.0 branch

```
roel@lucius:~/odoo/l10n-netherlands$ git shortlog -s -n
    29  Holger Brunn
     9  Stefan Rijnhart
     8  Diego Luis Neto
     5  astirpe
     4  StefanRijnhart
     3  Alexandre Fayolle
     3  Andrea Stirpe
     3  Stéphane Bidoul
     2  Yannick Vaucher
     1  Eric Caudal
     1  Kevin Graveman
     1  OCA Git Bot
     1  Roel Adriaans
     1  Stefan Rijnhart (Opener)
```

**Comment by RichDijk** [comment]
:+1: for @pankk

**Comment by ghost** [comment]
All, lets keep this discussion for the good sake of OCA. From my point of view is the added value of the representative is the one who can do that from different prospects in addition to coding, sharing, willing to improve and really community minded. 

Since all parties are willing to improve OCA's mission, I suggest to stay away from the discussion and start collaborating. There is a lot to do though. That gives much more positive energy than the struggle above. If it has to be @hbrunn  do the representativeness, congrats, why not? thats sharing isn't it? @pankk  and @astirpe should be the PSC. 

In this case there is a little guarantee for the collaboration for all involved parties.

Enjoy your day everybody.
