### ISSUE TITLE
XAF Audit file import as migration tool 

### ISSUE THREAD

**Issue by cjelsa** [OCA/l10n-netherlands#408]
**Is your feature request related to a problem?**
If so, please provide clear and concise description of what the problem is.
There is an export function for the Dutch Audit file but no import functionality

**Describe the solution you'd like**
As a way of migrating from Dutch (online) accounting software to Odoo

**Describe alternatives you've considered**
No real options yet

**Additional context**
Add any other context about the feature request here.

**Comment by thomaspaulb** [comment]
Are you aiming to import the whole of accounting history from the audit file? Or just the chart of accounts

**Comment by cjelsa** [comment]
Hi Thomas,

It would be a complete migration from for example Exact Online or Afas including full history on transaction detail level.

**Comment by thomaspaulb** [comment]
Interesting idea! Currently it would probably be possible to do this manually by using regular tools to convert (part of) the XML to CSV, and then importing that, but it's of course a lot of manual work.

**Comment by cjelsa** [comment]
I agree, so that is why I thought of the Audit file import. This should incentivise migrating to Oodoo a lot, especially if it would be user friendly.

**Comment by gjotten** [comment]
I do wonder who would ever create a module for this. As partners/integrators it's not that bad business-wise to just import manually and bill the hours.

For us, the amount of onboarding we do, put against the number of customers truly requiring a full financial import, compared to the amount of time needed to create this makes it a no-go. Would be nice if someone could ever sponsor it of course.

Incentivising migration to Odoo also works as lowering thresholds in a not-so-nice way for people who care about what we do here: a nice module with which one then simply fills an otherwise stock Enterprise installation with records, and no further synergies wrt OCA.
