### ISSUE TITLE
ICP Amount in Tax Report is double

### ISSUE THREAD

**Issue by PaulTammes** [OCA/l10n-netherlands#420]
In Module 10n_nl_tax_statement i make a report for a quarter, and all values look correct apart from the ICP transactions (3b, leveringen naar landen binnen de EU) where the amiunt is double that of the list you see when clicking on the PLUS  token next to it.

## Module
10n_nl_tax_statement

## Describe the bug
The listing created when clicking the plus sign is correct, somehow the script counts the values double

## To Reproduce
**Affected versions**:

1. Open the report (BTW rapport)
2. Set dates and refresh (bijwerken)
3. Look at outcome, note figure at 3b and click on plus sign

**Expected behavior**
Show correct amount (like in all other fields)

**Additional context**
Odoo16 on FreeBSD 14.1-release-p3 (with a custom wkhtmltopdf)

**Comment by gjotten** [comment]
@PaulTammes I can't replicate this error on our own 16.0 migration test instance which uses production data:

![image](https://github.com/user-attachments/assets/953b88f7-526c-4605-8867-6b1b02324eda)

![image](https://github.com/user-attachments/assets/8ae61f87-7704-494b-9117-d05047e854e8)

The total amount shown above corresponds 1-to-1 with what is on 3b in the overall report.

I suspect you have something unique going on in your db. Has it been migrated from a previous version?

**Comment by PaulTammes** [comment]
Yes weipgradedd from 14 tot 15 tot 16. Sny field/ taboes i should check on?

Met vriendelijke groet,

Paul Tammes

Sent from Proton Mail Android

-------- Original Message --------

**Comment by PaulTammes** [comment]
Sorry, was onderweg en mijn telefoon houdt er aparte spelling ideeën op na..

We zijn hebben van odoo14 naar 15 naar 16 de upgrade gedraaid en geen aparte foutmeldingen gehad.

Heb het script pas in versie 16 voor het eerst gedraaid, zijn er aparte tabellen of velden waar ik kan controleren op dubbele import oid?

Kan ook nog melden dat pas NA dat ik op post heb geklikt in de aangifte OB en de aangifte ICP er iets zichtbaar wordt in het ICP deel, is dat de normale werking of gaat daar misschien al iets mis?

Met vriendelijke groet,

Paul Tammes

Op dinsdag 1 oktober 2024 om 10:57 schreef Gijs-Jan Otten ***@***.***>:

**Comment by gjotten** [comment]
> Kan ook nog melden dat pas NA dat ik op post heb geklikt in de aangifte OB en de aangifte ICP er iets zichtbaar wordt in het ICP deel, is dat de normale werking of gaat daar misschien al iets mis?

That's how it's supposed to work. Only after the report's been finalized does the `l10n_nl_tax_statement_icp` module expect to be able to provide a full ICP overview for tax filing.

> Heb het script pas in versie 16 voor het eerst gedraaid, zijn er aparte tabellen of velden waar ik kan controleren op dubbele import oid?

What could be happening is that multiple lines on the same move (read: invoice) have the same tax tag set, or that tag mapping got jumbled somehow and multiple taxes point to the same tag.

To get an idea of what your problem is, you can:
- group the lines shown after clicking the (+) on Journal Entry
- click the top right settings button for the lines to also show 'Taxes' and 'Tax Grids'
- and what you'd _expect_ is to only see move lines posted to a revenue (i.e. 8xxx) account, with the `Verkopen export binnen EU` Tax, and the `+3b (omzet)` tag.
 
 If you see multiple move lines on the same move, for the same amount and the same taxes & tags, but on a different account (for example Debiteuren), then your tag mapping might be broken.

The `l10n_nl_tax_statement` module works via python code executing all kinds of searches and filtering on your account.move.lines aka boekingsregels.

It's interactive even, because when you press the update button, it again goes through `prepare_lines` , `compute_move_lines`, etc. You'll get different results if something's changed in the underlying lines.

So conceptually, A. it's not a script but , and B. what the report shows is 100% dependent on whether or not the underlying move lines have their 'stuff' set correctly.

We're also going beyond what might have looked like a technical issue to you, and into an implementation problem that's better handled somewhere else than this OCA repository.

**Comment by gjotten** [comment]
@OCA/local-netherlands-maintainers this one can be closed.
