### ISSUE TITLE
Alignment in report

### ISSUE THREAD

**Issue by woepwoep** [OCA/l10n-netherlands#49]
![image](https://cloud.githubusercontent.com/assets/3803292/16373354/1ded7c3e-3c52-11e6-86f6-23cffa1ab32a.png)

**Comment by woepwoep** [comment]
the above screenshot is from this module: l10n_nl_tax_declaration_reporting (author Onestein)

**Comment by lfreeke** [comment]
@woepwoep for time being you can solve it by changing the header spacing and top margin in the paper format at settings.

**Comment by espo-tony** [comment]
Hi,
I'm afraid this issue comes with the Odoo basic mechanism itself.
Basically, in Odoo and using QWeb report engine, the space reserved to the header is statically defined by the paper format used by the current report. As the "static definition" would suggest, there is no way to dynamically  adapt this space to what is really needed by the user. Default settings consider a space which is acceptable in most cases but that could not be in specific cases like the one posted above (in such example, we can see that the company's name is split due to its lenght). 

This issue is also common to basic Odoo reports (e.g.: invoice report) and should be solved case by case as part of the custom system settings just after the installation.
As Ifreeke suggested, the correct way to configure the header spacing in QWeb reports is to change the header spacing and top margin in the paper format settings. This can be performed by an user with technical features permissions through the menu "Reports" - "Technical" - "Reports" - "Paper Format" and choosing the paper format related to the report which one wants to fix (for this report, it's "European A4"). One can set the parameters choosing values that best suite its own installation.

Any other hardcode solution, such like adding a padding to the body of the report, enlarging the space reserved to the other, and so on, would fix the problem just for this specific case.

**Comment by woepwoep** [comment]
thx all for explaining the situation at hand.
best regards, Ron
