### ISSUE TITLE
Translating

### ISSUE THREAD

**Issue by ploegvde** [OCA/l10n-netherlands#64]
Hi,

I want to help by translation the Dutch modules. But it seems l10n-netherlands is not on Transifex.

**Comment by astirpe** [comment]
@ploegvde that would be great!

I don't know why l10n-netherlands is not on Transifex. Maybe @hbrunn knows the reason.

I think for the time being we can just add the `nl.po` file in the modules. You could open a pull request for adding the file, I guess such PRs will be well accepted from the Dutch Community.

I'm currently working on porting modules `l10n_nl_tax_declaration_reporting` and `10n_nl_xaf_auditfile_export` to Odoo V10. If you provide me with their `nl.po` files, I will merge them directly in the opened PRs, in order to speed up the approval/merging process. What do you think?

**Comment by hbrunn** [comment]
PRs work for now, but indeed we should have Transifex support. When I took over this project, I must admit I didn't check if this is activated (didn't even think of checking it to be honest), so I should now in order to make this more accessible for less technical contributors. Doesn't seem too complicated: https://github.com/OCA/maintainer-tools/wiki/Activate-Transifex - will do as soon as I find time, if anyone else wants to help a hand to speed up stuff that would be highly appreciated.

**Comment by ploegvde** [comment]
@astirpe I can provide you the nl.po file. Do i pull your code, install module and create po file? Or can you provide me the pot file?

**Comment by astirpe** [comment]
@ploegvde the way you prefer!

I would prefer if you do the pull, install and create the po file, is easier for me. And maybe is easier for you: this way you could pull, install, translate the terms directly in Odoo, then export the nl.po.

**Comment by ploegvde** [comment]
10n_nl_xaf_auditfile_export >> https://github.com/OCA/l10n-netherlands/pull/65

CLA i will send today.

**Comment by ploegvde** [comment]
l10n_nl_tax_declaration_reporting is not installable yet. When i can install i will translate. Ping me when i can start.

**Comment by astirpe** [comment]
Thank you @ploegvde ! With your permission I could include your `nl.po` file directly in PR #59 

I'm still working on `l10n_nl_tax_declaration_reporting` and sure I will ping you as soon I commit an installable version !!!

**Comment by ploegvde** [comment]
Of course, do whatever is needed.

**Comment by hbrunn** [comment]
if I didn't mess up anything, https://github.com/OCA/l10n-netherlands/pull/67 should activate transifex for the 10 branch. If this works, I'll provide the patches for 8 and 9 too, or whoever else feels so inclined.

**Comment by astirpe** [comment]
@ploegvde we have the Transifex up and running! Thanks to @hbrunn who spent his Sunday time on installing and testing it!

**Comment by hbrunn** [comment]
...and @astirpe who did the same. Will close this one then, thanks to everyone involved!

**Comment by ploegvde** [comment]
Yes, great, already thanked him in another issue. All modules are translated for V8, V9 and V10. Tanks a lot guys. Issue can be closed.
